name: reviewdog
on: 
  push:
    branches:
      - master
    pull_request:

jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Go Version 1.17
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      
      - name: Install linters
        run: go install golang.org/x/lint/golint@latest

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          workdir: "./lint"
